services:
  postgres:
    image: postgres:17
    container_name: meu-postgres
    restart: always
    environment:
      POSTGRES_DB: sistema_bibliotecario
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: